export default {
  login: 'nprymost',
  id: 111311598,
  node_id: 'U_kgDOBqJ67g',
  avatar_url: 'https://avatars.githubusercontent.com/u/111311598?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/nprymost',
  html_url: 'https://github.com/nprymost',
  followers_url: 'https://api.github.com/users/nprymost/followers',
  following_url: 'https://api.github.com/users/nprymost/following{/other_user}',
  gists_url: 'https://api.github.com/users/nprymost/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/nprymost/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/nprymost/subscriptions',
  organizations_url: 'https://api.github.com/users/nprymost/orgs',
  repos_url: 'https://api.github.com/users/nprymost/repos',
  events_url: 'https://api.github.com/users/nprymost/events{/privacy}',
  received_events_url: 'https://api.github.com/users/nprymost/received_events',
  type: 'User',
  site_admin: false,
  name: 'Natasha Prymost',
  company: null,
  blog: '',
  location: 'California',
  email: null,
  hireable: true,
  bio: null,
  twitter_username: null,
  public_repos: 7,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: '2022-08-15T19:35:36Z',
  updated_at: '2023-03-26T15:46:14Z',
};
